export {default as Home} from "./Home"
export {default as Hire} from "./Hire"
export {default as Job} from "./Job"
export {default as Login} from "./Login"
export {default as Register} from "./Register"
export {default as Resume} from "./Resume"